<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Acer-PC" name="Default test" tests="13" failures="1" timestamp="9 Sep 2019 12:12:15 GMT" time="0.404" errors="0">
  <testcase name="tc1" time="0.068" classname="org.cts.test.DataDriven.ParallelClassA"/>
  <testcase name="tc2" time="0.002" classname="org.cts.test.DataDriven.ParallelClassA"/>
  <testcase name="tc3" time="0.009" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.003" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.004" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.003" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.002" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.002" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.004" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.001" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.04" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.002" classname="org.cts.test.DataDriven.ParallelClassA">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.002" classname="org.cts.test.DataDriven.ParallelClassA">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.cts.test.DataDriven.ParallelClassA.tc3(ParallelClassA.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:969)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1148)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- tc3 -->
</testsuite> <!-- Default test -->
